# Generated by Django 3.2 on 2021-05-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0003_mascota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='catego'),
        ),
    ]
